tags:
  - Todos
summary: Atualizar um todo de um usuário
description: Dado um id, título e descrição, gera um atualização do todo do usuário no banco de dados.
security:
  - Bearer token: []

parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    description: id do todo

requestBody:
  description: Corpo da requisição
  required: true

  content:
    application/json:
      schema:
        type: object
        properties:
          title:
            type: string
          description:
            type: string

        example:
          title: título do todo atualizado
          description: descrição do todo atualizado

responses:
  '200':
    description: todos do usuário atualizado
    content:
      application/json:
        schema:
          type: object
          properties:
            todos:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    example: 'todo_id'
                  userId:
                    type: string
                    example: 'user_id'
                  title:
                    type: string
                    example: 'todo title'
                  description:
                    type: string
                    example: 'todo description'

        example:
          todos:
            - id: todo_id
              userId: user_id
              title: todo title
              description: todo description

  '401':
    description: Você não possui um token válido
  '404':
    description: Você não possui informações desse usuário para atualização
  '500':
    description: Erro interno do servidor
