  tags:
    - Users
  summary: Criar um token
  description: Dado um usuário e senha, cria um token.

  requestBody:
    description: Corpo da requisição
    required: true

    content:
      application/json:
        schema:
          type: object
          properties:
            username:
              type: string
            password:
              type: string

          example:
            username: user_name
            password: Abc123

  responses:
    '201':
      description: ok
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
                description: The user token.

          example:
            token: 'token'

    '400':
      description: Username e/ou senha estão incorretos
    '500':
      description: Erro interno do servidor
